Trainings/AngularJS Trainings/LiksManager/LiksManager/Models/ILinkRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LinksManager.Models
{
    interface ILinkRepository
    {
        List<LinkEntity> GetAll();
        int InsertLink(LinkEntity link);

    }
}

Trainings/AngularJS Trainings/LiksManager/LiksManager/Models/LinkEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LinksManager.Models
{
    public class LinkEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

Trainings/AngularJS Trainings/LiksManager/LiksManager/Models/SqlLinRepository.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace LinksManager.Models
{
    public class SqlLinRepository : ILinkRepository
    {
        private string _connectionString;

        private const string GetAllQuery = "SELECT Id, Name, Url FROM tblLinks;";
        private const string InsertLinkQuery = "INSERT INTO tblLinks (Name, Url) VALUES (@name, @url);";

        public SqlLinRepository(string connectionString)
        {
            this._connectionString = connectionString;
        }

        public List<LinkEntity> GetAll()
        {
            using (SqlConnection connection = new SqlConnection(this._connectionString))
            {
                connection.Open();
                
                using (SqlCommand command = new SqlCommand(GetAllQuery, connection))
                {
                    List<LinkEntity> result = new List<LinkEntity>();
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            result.Add(new LinkEntity
                            {
                                Id = int.Parse(reader["Id"].ToString()),
                                Name = reader["Name"].ToString(),
                                Url = reader["URL"].ToString()
                            });
                        }
                        return result;
                    }
                }
            }
        }

        public int InsertLink(LinkEntity link)
        {
            using(SqlConnection connection = new SqlConnection(this._connectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand(InsertLinkQuery, connection))
                {
                    command.Parameters.AddWithValue("@name", link.Name);
                    command.Parameters.AddWithValue("@url", link.Url);

                    return command.ExecuteNonQuery();
                }
            }
        }
    }
}

Trainings/AngularJS Trainings/LiksManager/LiksManager/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LinksManager.Models;
using System.Configuration;

namespace LiksManager.Controllers
{
    public class LinksController : Controller
    {
        ILinkRepository _sqlLinkRepo;

        public LinksController()
        {
            this._sqlLinkRepo = new SqlLinRepository(ConfigurationManager.ConnectionStrings["LinkStorageConnection"].ConnectionString);        
        }
        // GET: Links
        [HttpGet]
        public ActionResult Index()
        {
            var links = this._sqlLinkRepo.GetAll();
            return View(links);
        }
        [HttpPost]
        public ActionResult InsertLink(string linkName, string URL)
        {
            var linksBefore = this._sqlLinkRepo.GetAll();
            int result = this._sqlLinkRepo.InsertLink(new LinkEntity
            {
                Name = linkName,
                Url = URL
            });
            var linksAfter = this._sqlLinkRepo.GetAll();
            if (result > 0)
            {
                return View("Index", linksAfter);
            }
            else
            {
                return View("Index", linksBefore);
            }
        }
        
    }
}

Trainings/AngularJS Trainings/LiksManager/LiksManager/Views/Links/Index.cshtml
@model List<LinksManager.Models.LinkEntity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<h4>Add new useful link</h4>
@using (Html.BeginForm("InsertLink", "Links", FormMethod.Post))
{
    <div>
        Name : @Html.TextBox("linkName")
        URL :  @Html.TextBox("URL")
        <input type="submit" value="Add"/>
    </div>
}
<table>
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var link in Model)
        {
            <tr>
                <td>
                    @link.Id
                </td>
                <td>
                    <a href="@link.Url">@link.Name</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Trainings/AngularJS Trainings/LiksManager/LiksManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @RenderSection("Styles", false)
    @RenderSection("HeadScripts", false)
    <script src="~/Scripts/pages/links/angular.js"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("FootScripts", false)
</body>
</html>